/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

//random
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:22cb8d05-f00a-4ff4-b695-f18171111b86",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9Ezx02xYB",
    "aws_user_pools_web_client_id": "7qt4mrh0vnodidcgl7oo1ka7mg",
    "oauth": {}
};


export default awsmobile;
